"""Supabase transport. Caller-scoped metadata queries keep RLS effective."""
from urllib.parse import quote
from uuid import UUID

import httpx
from fastapi import HTTPException

from backend.app.core.auth import Principal
from backend.app.core.config import get_settings

MIME = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
MIMES = {"docx": MIME, "pdf": "application/pdf"}
BUCKET = "stegashield-originals"


class Gateway:
    def __init__(self, settings=None, transport=None):
        self.settings = settings or get_settings()
        self.transport = transport
        self.url = self.settings.supabase_url.rstrip("/")
        if not self.url.startswith("https://") or not self.settings.supabase_secret_key:
            raise HTTPException(503, "Supabase gateway configuration is incomplete.")

    def headers(self, user=None):
        if user:
            return {"apikey": self.settings.supabase_publishable_key, "Authorization": f"Bearer {user.token}"}
        # New sb_secret keys belong in apikey, not the JWT Authorization header.
        key = self.settings.supabase_secret_key
        result = {"apikey": key}
        if not key.startswith("sb_secret_"):
            result["Authorization"] = f"Bearer {key}"
        return result

    def request(self, method, path, *, user=None, **kwargs):
        headers = self.headers(user)
        prefer = kwargs.pop("prefer", None)
        if prefer:
            headers["Prefer"] = prefer
        try:
            with httpx.Client(transport=self.transport, timeout=15) as client:
                response = client.request(method, self.url + path, headers=headers, **kwargs)
            if response.status_code in (401, 403):
                raise HTTPException(403, "Access denied.")
            if response.status_code == 409:
                raise HTTPException(409, "This record already exists or conflicts with an existing record.")
            response.raise_for_status()
            return response.json() if response.content else None
        except (httpx.HTTPError, ValueError):
            raise HTTPException(503, "Document service unavailable.") from None

    def rows(self, table, user, **filters):
        rows = self.request("GET", "/rest/v1/" + table, user=user, params=filters)
        if not isinstance(rows, list):
            raise HTTPException(503, "Invalid database response.")
        return rows

    def document(self, document_id: UUID, user: Principal):
        rows = self.rows("documents", user, id=f"eq.{document_id}", archived_at="is.null", select="*")
        if len(rows) != 1:
            raise HTTPException(404, "Document not found or unavailable.")
        document = rows[0]
        if user.role != "admin":
            permissions = self.rows("document_permissions", user,
                document_id=f"eq.{document_id}", user_id=f"eq.{user.id}", select="expires_at")
            from datetime import datetime, timezone
            if not permissions or (permissions[0]["expires_at"] is not None and
                datetime.fromisoformat(permissions[0]["expires_at"].replace("Z", "+00:00")) <= datetime.now(timezone.utc)):
                if self.request("POST", "/rest/v1/rpc/has_position_access", user=user,
                                json={"p_document_id": str(document_id)}) is not True:
                    raise HTTPException(404, "Document not found or unavailable.")
        if document["format"] not in MIMES or (document["format"] == "pdf" and not self.settings.pdf_enabled):
            raise HTTPException(415, "Document format is not enabled.")
        return document

    def original(self, document):
        # Object paths are generated by this API, never supplied by download clients.
        path = document["storage_path"]
        format = document.get("format", "docx")
        if format not in MIMES or path != f"{UUID(document['id'])}/original.{format}":
            raise HTTPException(503, "Invalid original document location.")
        try:
            with httpx.Client(transport=self.transport, timeout=15) as client:
                with client.stream("GET", self.url + f"/storage/v1/object/{BUCKET}/{quote(path, safe='/')}", headers=self.headers()) as response:
                    response.raise_for_status()
                    data = bytearray()
                    for chunk in response.iter_bytes(65536):
                        data.extend(chunk)
                        if len(data) > self.settings.max_upload_size_bytes:
                            raise HTTPException(503, "Stored original exceeds size limit.")
                    return bytes(data)
        except httpx.HTTPError:
            raise HTTPException(503, "Original storage unavailable.") from None

    def store_original(self, path, data):
        try:
            with httpx.Client(transport=self.transport, timeout=30) as client:
                response = client.post(self.url + f"/storage/v1/object/{BUCKET}/{path}",
                    headers={**self.headers(), "Content-Type": MIMES[path.rsplit('.', 1)[-1]], "x-upsert": "false"}, content=data)
                response.raise_for_status()
        except httpx.HTTPError:
            raise HTTPException(503, "Original storage unavailable.") from None

    def record_download(self, user, document_id, token, digest, ip, agent):
        return self.request("POST", "/rest/v1/rpc/record_download", json={
            "p_user_id": str(user.id), "p_document_id": str(document_id),
            "p_token": str(token), "p_sha256": digest, "p_ip": ip, "p_user_agent": agent,
            "p_session_id": str(user.session_id) if user.session_id else None})

    def lookup(self, token, user):
        rows = self.rows("download_events", user, watermark_token=f"eq.{token}", select="id,user_id,document_id,downloaded_at,protected_sha256")
        return rows[0] if len(rows) == 1 else None

    def audit(self, record):
        self.request("POST", "/rest/v1/forensic_events", json=record)


def get_gateway():
    return Gateway()
